language: java
compiler: gcc
jdk: oraclejdk8
env:
 global:
  - CC=gcc-4.9
branches:
 except:
  - svn/test-perf
  - svn/unstable
  - svn/issue11
  - svn/v4j
  - svn/fix-delay
  - svn/add-sse
  - svn/switch-input
  - svn/tags/0.9.0
  - svn/trunk
  - svn/tidyup
  - master-old
before_install:
 - sudo -E add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo -E apt-get -yq update
 - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-4.9 libc-bin libc-dev-bin libc6-dev
 - sudo -E ldconfig
install:
 - make -C libvideo all -j4
 - ant jnilib-debug all-debug include-jni jar-test
 - sudo -E ant install
script:
 - ant test-junit
