language: java
compiler: gcc
jdk: oraclejdk8
addons:
 apt:
  packages:
   - gcc
   - libc-bin
   - libc-dev-bin
   - libc6-dev
env:
 global:
  - CC=gcc
branches:
 except:
  - svn/test-perf
  - svn/unstable
  - svn/issue11
  - svn/v4j
  - svn/fix-delay
  - svn/add-sse
  - svn/switch-input
  - svn/tags/0.9.0
  - svn/trunk
  - svn/tidyup
  - master-old
before_install:
 - sudo ldconfig
install:
 - make -C libvideo all -j4
 - ant jnilib-debug all-debug include-jni jar-test
 - sudo ant install
script:
 - ant test-junit
